spring.application.name=Inventory_system
spring.datasource.url= jdbc:postgresql://inventorydatabase_04f4_user:r9WM1hn2YAdklrQOlljPYf6ws6tyBb0K@dpg-d9lv74jm8hqs739hk010-a/inventorydatabase_04f4
spring.datasource.username=inventorydatabase_04f4_user
spring.datasource.password=r9WM1hn2YAdklrQOlljPYf6ws6tyBb0K

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true